### ISSUE TITLE
KRaft mode / Kafka without Zookeeper

### ISSUE THREAD

**Issue by lindt** [confluentinc/examples#1008]
**Description**

Kafka 2.8 (used since Confluent version 6.2) zookeeper is not required anymore and kafka could run in KRaft mode.
The current docker images could not run in KRaft mode, they require zookeeper settings.
Please add the possibility to utilize KRaft mode.

[Kraft Mode in Confluent Blog](https://www.confluent.de/blog/kafka-without-zookeeper-a-sneak-peek/)

**Comment by ybyzek** [comment]
@lindt have you seen this [KRaft + Docker documentation](https://docs.confluent.io/platform/current/tutorials/build-your-own-demos.html#kraft)?

**Comment by lindt** [comment]
thanks, is working.
was confused, cause the Dockerimage itself requires the Zookeeper, but get's sed-patched.

BTW: kraft mode works like a charm. thanks!
