### ISSUE TITLE
Using some of the util classes from the examples

### ISSUE THREAD

**Issue by elliotcm** [confluentinc/examples#101]
Hi there,

We're writing a processor using kafka streams and would like to make use of some of the util classes in this repo.

Although there's a `pom.xml` for the streams examples it doesn't seem to be on a public repository anywhere, so I went ahead and installed it locally using maven.

This got me as far as using e.g. the `GenericAvroSerde`, but the built package doesn't include the test classes so classes like `IntegrationTestUtils` are not available for use in our own integration tests.

Based on my reading it seems like it's typical to create another pom file for the test classes, but I'm not well experienced with maven so I could well be wrong here.

What would be the best way to go about this, without copy/pasting the helper classes?

Thanks,
Elliot

**Comment by elliotcm** [comment]
After some further digging (which I probably should've done first) I notice https://github.com/confluentinc/schema-registry/pull/442 and https://github.com/confluentinc/examples/issues/87 discuss similar issues.

I'm assuming this is ongoing and I'd be happy to see them released properly, but in the meantime is there something I can do to make use of them?

**Comment by elliotcm** [comment]
I've managed to find https://maven.apache.org/plugins/maven-jar-plugin/test-jar-mojo.html which has got me unblocked.  Will close this issue.

**Comment by miguno** [comment]
FYI @elliotcm: In our next major release of Confluent Platform we will ship [Confluent schema registry](https://github.com/confluentinc/schema-registry) aware Kafka Streams serdes for generic Avro and for specific Avro.  See https://github.com/confluentinc/schema-registry/tree/master/avro-serde, which is already available in the `master` development branch of Confluent schema registry.

**Comment by elliotcm** [comment]
@miguno That's great news, thanks.  We'll definitely make use of them.

We're actually finding that including the JARs for the examples is a bad way to get the classes we need since the dependencies cause all sorts of complications, so we'll likely still run a custom JAR to provide the `IntegrationTest` class, embedded zookeeper etc.

**Comment by miguno** [comment]
@elliotcm:  Yes, improving the test toolkit is still on our TODO list.  We definitely haven't forgotten about it.

In the meantime, you may want to consider reading https://lists.apache.org/thread.html/c41c3fa96e56ffd30f13475cd4869fde027b32597da0d7767fa70388@%3Cusers.kafka.apache.org%3E to get Apache Kafka's test-related classes for Kafka Streams.

```xml
<dependency>
  <groupId>org.apache.kafka</groupId>
  <artifactId>kafka_2.11</artifactId>
  <version>0.10.2.0</version>
  <classifier>test</classifier>
  <scope>test</scope>
</dependency>
```

Note though that the Kafka project does not provide any contract/guarantee for these classes (cf. `<classifier>test</classifier>`); i.e., we do not guarantee that the next Kafka version will not rename classes, change methods, etc.  The current plan is that the Kafka project will provide a dedicated test toolkit with an "official" artifact.  I hope my explanation makes sense. :-)

**Comment by elliotcm** [comment]
@miguno That does make sense, but there's one piece of the puzzle missing.

The confluent examples integration tests make use of classes like `EmbeddedSingleNodeKafkaCluster` which are not available in the kafka test helpers.  To what degree would I still need to copy/paste classes like these vs using classes direct from the kafka test package?

**Comment by miguno** [comment]
@elliotcm: [EmbeddedKafkaCluster.java](https://github.com/apache/kafka/blob/trunk/streams/src/test/java/org/apache/kafka/streams/integration/utils/EmbeddedKafkaCluster.java) in Apache Kafka is essentially the same as `EmbeddedSingleNodeKafkaCluster` in this repo.  The only real difference is that the AK variant does not start Confluent schema registry as well (because the Apache Kafka code base does not know about Confluent schema registry).
