### ISSUE TITLE
[Question] How do you get a reference to WikiFeed class

### ISSUE THREAD

**Issue by MarcMagnin** [confluentinc/examples#102]
Hi,

In the Avro examples you are using the class io.confluent.examples.streams.avro.WikiFeed
WifiFeed is from an Avro schema and I can't get any reference to any classes.
How do you generate classes for such schema?

Many thanks,
Marc

**Comment by miguno** [comment]
Run `mvn compile` in the `kafka-streams` folder.

**Comment by MarcMagnin** [comment]
Thanks, I wasn't using the examples repo ;)
