### ISSUE TITLE
How to generate the messages in JSON Schema format

### ISSUE THREAD

**Issue by RezaRahmatiCmor** [confluentinc/examples#1051]
Hi

We are publishing the messages to kafka using examples in this repo, then there is an issue with ksql/postgres connector that are not able to put our messages in db, 
Based on this [link](https://docs.confluent.io/platform/current/schema-registry/serdes-develop/serdes-json.html#json-schema-serializer-and-deserializer) seems the messages should be send in JSON Schema format, the example and classes are in Java, wondering how we can do that in C# 

and [here](https://rmoff.net/2020/07/03/why-json-isnt-the-same-as-json-schema-in-kafka-connect-converters-and-ksqldb-viewing-kafka-messages-bytes-as-hex/) is another link how some magic bytes make the JSON and JSON Schema messages different

**Comment by rspurgeon** [comment]
Hi @RezaRahmatiCmor, I think you will have better luck by posting your question to the Confluent Forum. https://forum.confluent.io/   When posting your question, please be as specific as possible with code and configuration examples. 

There are more experts monitoring the boards there and if you tag me I can try and source you an answer. In the meantime, I'm going to close this issue in favor of the question on the forum.  Thanks
