### ISSUE TITLE
Simaple Avro Producer Example is not working

### ISSUE THREAD

**Issue by ADDale** [confluentinc/examples#108]
I am trying to run the simple avro producer under 
examples / clients / avro / src / main / java / io / confluent / examples / clients / basicavro / ProducerExample.java 

I am using the gradle and I was not able to ad the avro gradle plugin in build file which can convert avsc file to java classes.

I have manually created the  payment class and trying to run the code but I am getting below error.

Exception in thread "main" org.apache.kafka.common.errors.SerializationException: Error serializing Avro message
Caused by: java.lang.IllegalArgumentException: Unsupported Avro type. Supported types are null, Boolean, Integer, Long, Float, Double, String, byte[] and IndexedRecord
	at io.confluent.kafka.serializers.AbstractKafkaAvroSerDe.getSchema(AbstractKafkaAvroSerDe.java:129)
	at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.serializeImpl(AbstractKafkaAvroSerializer.java:76)
	at io.confluent.kafka.serializers.KafkaAvroSerializer.serialize(KafkaAvroSerializer.java:53)
	at org.apache.kafka.common.serialization.ExtendedSerializer$Wrapper.serialize(ExtendedSerializer.java:65)
	at org.apache.kafka.common.serialization.ExtendedSerializer$Wrapper.serialize(ExtendedSerializer.java:55)
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:854)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:816)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:703)
	at Test.ProducerExample.main(ProducerExample.java:39)
..

Can you please confirm is it mandatory to get java class generated from avsc file itself and code wont work with Manaul java class creation?

Also can you share how can we achieve this with gradle?

**Comment by OneCricketeer** [comment]
> I have manually created the payment class 

Does that class `extends SpecificRecord`? 

If not, then it is not an `IndexedRecord` that is expected by the `KafkaAvroSerializer`, and so won't work. 

This Gradle plugin was mentioned on Confluent Slack channel https://plugins.gradle.org/plugin/com.github.imflog.kafka-schema-registry-gradle-plugin

**Comment by ADDale** [comment]
Hi Jordan,

Thanks for the reply. so you mean if my pojo extends SpecificRecord, then KafkaAvroSerializer will work and  custom serializer wont be needed?

**Comment by OneCricketeer** [comment]
That's right, but you would ideally get a SpecificRecord from a schema, not writing a `.java` file manually, either using `avro-tools.jar`, or using a Maven/Gradle plugin 

The Maven usage is shown in the Avro documentation, and referred to by the above tutorial
https://avro.apache.org/docs/current/gettingstartedjava.html

You might also be able to use Jackson (based on your other issue posting) - https://github.com/FasterXML/jackson-dataformats-binary/tree/master/avro#generating-avro-schema-from-pojo-definition

**Comment by ADDale** [comment]
Thanks for confirmation Jordan. Let me try it  that way and I would share the outcome :)

**Comment by ADDale** [comment]
Thanks for your help Jordan. I has used avro-tools.jar  and was able to register schema and consume the messages.

**Comment by rakeshbgupta** [comment]
Hi Guys,

Thanks for the useful post.

I am also dealing with a simillar issue, wud be great to get your view point as well.

I am getting data from gRPC server into my java client application as Java objects (classes generated/provided by the gRPC service from .proto fles), I want to create avro records from this java object before sending it to the kafka topic.

I have the schema of the protobuf objects and the corresponding java object (JavaProto.class), but how to I generate avro records from these?:
```
//Get schema of  protobuf object
        ProtobufData protobufData = ProtobufData.get();
        Schema protoSchema = protobufData.getSchema(JavaProto.class);

// Get generic avro records
            JavaProto returnedGRPCData;
            GenericRecord avroRec =  new GenericData.Record(protoSchema);
            ???avroRec.put(returnedGRPCData);???

// Send data to kafka            
ProducerRecord producerRec = new ProducerRecord<String, GenericRecord>("topic", 
       returnedGRPCData.getId(), avroRec);
         
         producer.send(producerRec);
```
Any help will be highly appreciated...

**Comment by rakeshbgupta** [comment]
Thanks for the useful post.

I am also dealing with a simillar issue, wud be great to get your view point as well.

I am getting data from gRPC server into my java client application as Java objects (classes generated/provided by the gRPC service from .proto fles), I want to create avro records from this java object before sending it to the kafka topic.

I have the schema of the protobuf objects and the corresponding java object (JavaProto.class), but how to I generate avro records from these?:

```
//Get schema of  protobuf object
        ProtobufData protobufData = ProtobufData.get();
        Schema protoSchema = protobufData.getSchema(JavaProto.class);

// Get generic avro records
            JavaProto returnedGRPCData;
            GenericRecord avroRec =  new GenericData.Record(protoSchema);
            ???avroRec.put(returnedGRPCData);???

// Send data to kafka            
ProducerRecord producerRec = new ProducerRecord<String, GenericRecord>("topic", 
       returnedGRPCData.getId(), avroRec);
         
         producer.send(producerRec);
```
Any help will be highly appreciated...

**Comment by OneCricketeer** [comment]
@rakeshbgupta Schema Registry now supports Protobuf, by the way

**Comment by rakeshbgupta** [comment]
Earlier, it was a work in progress, not officially supported. But even if it does support, it will be months before we upgrade to the latest version, so for now I still need go work on this :)

**Comment by nicolaemarasoiu** [comment]
Hi, I am getting same error. My UserEvent was generated form schema..
