### ISSUE TITLE
KStream- Multi KTable Join Operation 

### ISSUE THREAD

**Issue by chenbekor** [confluentinc/examples#111]
Is it possible to perform multi join operations between one Kstream  and multiple KTables ? if so - what would be the right choice to partition the keys? (In our case, each KTable has a different type of primary key so the vanilla example of click stream and user GEO locations  does not cover more advanced use cases such as: sales stream containing user id and product id => joined with a User Table (partitioned by user id) and a Product Table (partitioned by product_id)

**Comment by mjsax** [comment]
This KIP explains your options pretty good: https://cwiki.apache.org/confluence/display/KAFKA/KIP-99%3A+Add+Global+Tables+to+Kafka+Streams

Btw: it's better to ask questions at https://groups.google.com/forum/#!forum/confluent-platform.

Closing this for now as we actually don't take Github JIRAs :)
