### ISSUE TITLE
mvn clean fails because of missing version for Confluent log4j 

### ISSUE THREAD

**Issue by Scharlotten** [confluentinc/examples#1119]
**Description**
When running mvn clean, it fails with the following error:
![image](https://user-images.githubusercontent.com/23079698/182198888-d195c1c0-40f3-4805-8ade-5c24bfc097c9.png)

I added the latest version in the pom, with <version>1.2.17-cp9</version> - that fixed the issue.

**Comment by ybyzek** [comment]
@Scharlotten thanks for filing the issue, I can reproduce it as well.

Fails:
- 7.2.1
- 7.2.0

Passes:
- 7.1.2
