### ISSUE TITLE
 org.apache.kafka.common.network.Selector - Connection with /127.0.0.1 disconnected

### ISSUE THREAD

**Issue by anandreddyakidi** [confluentinc/examples#116]
I am trying to use EmbeddedSingleNodeKafkaCluster.java from the examples for writing unit test cases of my application. Getting below Exception. Please help me with the Exception. Thanks in Advance.

```
[kafka-network-thread-0-ListenerName(PLAINTEXT)-PLAINTEXT-2] DEBUG org.apache.kafka.common.network.Selector - Connection with /127.0.0.1 disconnected
java.io.EOFException: null
	at org.apache.kafka.common.network.NetworkReceive.readFromReadableChannel(NetworkReceive.java:83)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:71)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:169)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:150)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:355)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:303)
	at kafka.network.Processor.poll(SocketServer.scala:494)
	at kafka.network.Processor.run(SocketServer.scala:432)
	at java.lang.Thread.run(Thread.java:745)
```

Regards
Anand

**Comment by miguno** [comment]
Is this actually causing a problem?  Note the log level of `DEBUG`.  This could be a simply notification log message that a TCP connection was closed.

**Comment by anandreddyakidi** [comment]
after that getting below log:

16:19:09.966 [main] DEBUG org.apache.kafka.common.metrics.Metrics - Removed sensor with name connections-closed:
16:19:09.967 [main] DEBUG org.apache.kafka.common.metrics.Metrics - Removed sensor with name connections-created:
16:19:09.967 [main] DEBUG org.apache.kafka.common.metrics.Metrics - Removed sensor with name bytes-sent-received:
16:19:09.967 [main] DEBUG org.apache.kafka.common.metrics.Metrics - Removed sensor with name bytes-sent:
16:19:09.967 [main] DEBUG org.apache.kafka.common.metrics.Metrics - Removed sensor with name bytes-received:
16:19:09.967 [main] DEBUG org.apache.kafka.common.metrics.Metrics - Removed sensor with name select-time:
16:19:09.967 [main] DEBUG org.apache.kafka.common.metrics.Metrics - Removed sensor with name io-time:
16:19:09.968 [main] INFO kafka.network.SocketServer - [Socket Server on Broker 0], Shutting down

**Comment by miguno** [comment]
This are `DEBUG` log messages, and do not indicate any problems.  Everything is working correctly from what I can tell.

**Comment by saritseal** [comment]
The server stopped without any issues, but what is the reason for this exception
