### ISSUE TITLE
Can we have example with custom Pojos ?

### ISSUE THREAD

**Issue by sohimankotia** [confluentinc/examples#122]
@miguno  I was trying example where input comings as json string . And while consuming I was converting them into custom pojos like PageViews and UserProfiles . But while doing left join I was getting class cast exceptions . It would be great if there is end to end example which will use custom java objects with custom serde instead of using Avro .
I have put my code in confluent forum but did not get solution . [Class Cast Exception while Left Join in Streams](https://groups.google.com/forum/#!topic/confluent-platform/DFpIpHSiWas)

**Comment by miguno** [comment]
We already have such examples, @sohimankotia.  See [KafkaMusicExample.java](https://github.com/confluentinc/examples/blob/3.2.x/kafka-streams/src/main/java/io/confluent/examples/streams/interactivequeries/kafkamusic/KafkaMusicExample.java), for instance, which includes a `TopFiveSerde implements Serde<TopFiveSongs> ` (here, `TopFiveSongs` is a custom POJO).

**Comment by sohimankotia** [comment]
Thanks you very much for pointer @miguno
