### ISSUE TITLE
Cloud ETL example does not work with Confluent CLI 4.x

### ISSUE THREAD

**Issue by metadaddy** [confluentinc/examples#1262]
**Description**
I recently tried to work through the [Cloud ETL example](https://github.com/confluentinc/examples/tree/7.5.0-post/cloud-etl), but hit numerous issues due to the [breaking changes in Confluent CLI 4.x](https://docs.confluent.io/confluent-cli/current/migrate.html#cli-breaking-changes-v4). For example, `ccloud::enable_schema_registry()` invokes a command of the form:

```
confluent schema-registry cluster enable --cloud aws --geo us
```

which results in an error:

```
Error: unknown flag: --cloud
Usage:
  confluent schema-registry cluster [command]

Available Commands:
  describe    Describe the Schema Registry cluster for this environment.
  update      Update global mode or compatibility of Schema Registry.

Global Flags:
  -h, --help            Show help for this command.
      --unsafe-trace    Equivalent to -vvvv, but also log HTTP requests and responses which might contain plaintext secrets.
  -v, --verbose count   Increase verbosity (-v for warn, -vv for info, -vvv for debug, -vvvv for trace).

Use "confluent schema-registry cluster [command] --help" for more information about a command.
```

The [documentation states that CLI 3.0.0 or later is required](https://docs.confluent.io/cloud/current/get-started/tutorials/cloud-etl.html#local-tools), but this is no longer accurate. Also, at the time, I was unable to find a location from which I could download a 3.x.x version of the CLI.

I [figured out the changes to get it working with CLI 4.4.0](https://github.com/backblaze-b2-samples/confluent-examples/commit/918cc6d5dc3ce4408c72ed4dc62d49124556370c), but my scope was limited to the Cloud ETL example, so I'm hesitant to submit a PR. Unfortunately, I don't have the time or knowledge to migrate all of the examples to CLI 4.x.

I'm guessing (hoping?) that someone at Confluent is on the case, and already migrating the examples to CLI 4.x, so this is mostly to help anyone else that encounters the same issues, and point the way to the [Confluent CLI v3.65.0 download links on GitHub](https://github.com/confluentinc/cli/releases/tag/v3.65.0) that I since found (assuming that CLI version works!).

In the interim, you might also want to update the docs to state that _only_ 3.x.x CLI versions work, rather than 3.0.0 and above, and include the link to download Confluent CLI v3.65.0.

Also, many of the docs have moved, but there are no redirects. For example, the Cloud ETL example points to `https://docs.confluent.io/platform/current/tutorials/examples/cloud-etl/docs/index.html` (utm query params removed for clarity), but the doc is now at `https://docs.confluent.io/cloud/current/get-started/tutorials/cloud-etl.html`.

**Comment by davetroiano** [comment]
Thank you for raising this @metadaddy! I fixed with [this](https://github.com/confluentinc/examples/pull/1263) PR which is essentially your changes plus a couple of other small cleanups. The [docs](https://docs.confluent.io/cloud/current/get-started/tutorials/cloud-etl.html) page is updated too -- both the v4 CLI requirement and it points to the `master` branch of the `examples` repo instead of the nonexistent `current-post` branch. We're fixing the redirect issue too.

**Comment by metadaddy** [comment]
Thanks for the update, @davetroiano! 👍🏻
