### ISSUE TITLE
Gradle and Maven unable to find streams-examples 

### ISSUE THREAD

**Issue by alexdwx** [confluentinc/examples#135]
I'm getting this error.

`Could not find io.confluent:streams-examples:3.2.2.`

I have this in my build.gradle file.
```
maven {
    url "http://packages.confluent.io/maven/"
}
compile "io.confluent:streams-examples:3.2.2"
```

**Comment by ewencp** [comment]
@alexdwx We're not currently publishing these examples. They are intended to be examples of how an user would write applications using Kafka and Confluent, so they are setup to be easy to build and run yourself.
