### ISSUE TITLE
prefilling globalKTable before joining stream

### ISSUE THREAD

**Issue by vijab** [confluentinc/examples#140]
Hi,
I have a use-case where i need to join 2 topics, A and B. The topic-A has almost static data (not much of changes coming in) whereas topic-B gets around 800-1000 events/second. I would like to join these 2 topics and wanted to use GlobalKTable to load all data from topic-A. My question is, is there anyway I can pre-load all the data from topic-A into a globalKTable before I start processing/enriching events from topic-B?
thanks,
vijai

**Comment by mjsax** [comment]
This happens automatically. A `GlobalKTable` is always full populated before and other processing starts.
