### ISSUE TITLE
Example with Kafka Stream + Scala + Avro

### ISSUE THREAD

**Issue by jocelyndrean** [confluentinc/examples#152]
Hi guys ! Is it planned to add an example with Kafka Stream + Scala + Avro ? I could work on it and submit a PR if I can get some help from you guys ^^.

**Comment by guozhangwang** [comment]
@jocelyndrean Thanks for your interest, we are moving the streams-examples from this repo to https://github.com/confluentinc/kafka-streams-examples. It has similar content to the current `streams` folder, you are welcome to check if we do not have an example with Streams + Scala + Avro yet.

cc @miguno

**Comment by miguno** [comment]
Good news, we already have such examples @jocelyndrean. :-)

See the folder `kafka-streams/src/test/scala/io/confluent/examples/streams`:

* `GenericAvroScalaIntegrationTest.scala`
* `SpecificAvroScalaIntegrationTest.scala`

**Comment by miguno** [comment]
The examples for Avro in Scala are actually also listed in the "Available Examples" section for Scala, see https://github.com/confluentinc/examples/tree/3.3.0-post/kafka-streams#examples-scala.

What would help is if you could tell us where you tried to find such an example?  This would allow us to e.g. improve the docs if need be?

**Comment by jocelyndrean** [comment]
Awesome ! Thanks @guozhangwang @miguno for you feedback ! :)
My bad, I didn't see the examples with Scala inside the test folder :/ So, I will try to reproduce a small example (but with SBT). Do you have recommendation for a sbt plugin for Avro ?
Thank you again guys for your quick answers :)

**Comment by miguno** [comment]
These two sbt plugins are popular for Avro:

https://github.com/sbt/sbt-avro
https://github.com/julianpeeters/sbt-avrohugger

**Comment by jocelyndrean** [comment]
Thanks :) :) :)
