### ISSUE TITLE
Cloud ACL script has a bug in parsing the API Secret 

### ISSUE THREAD

**Issue by ScottGriz** [confluentinc/examples#174]
https://github.com/confluentinc/examples/blob/5.2.1-post/ccloud/acl.sh . 

Line 164 API_SECRET_SA=$(echo "$OUTPUT" | grep "\| Secret" | awk '{print $4;}')
The Double quotes around $OUTPUT cause a bogus string to be put in the client.config
I changed the code to 
API_SECRET_SA=$(echo "$OUTPUT" | grep '| Secret' | awk '{print $4;}')
Same as the API_KEY and now  works.  client.config is built with the correct API_SECRET_SA value

**Comment by ybyzek** [comment]
Resolved in #176
