### ISSUE TITLE
demo-consumer-1 group is hard coded in java consumer client so fails on ACL

### ISSUE THREAD

**Issue by ScottGriz** [confluentinc/examples#175]
https://github.com/confluentinc/examples/blob/5.2.1-post/ccloud/acl.sh
Line 315
ccloud kafka acl create --allow --service-account-id $SERVICE_ACCOUNT_ID --operation READ --consumer-group java_example_group_1
Creates an ACL for java_example_group_1 but the java client hard codes group to demo-consumer-1 

Caused by: org.apache.kafka.common.errors.GroupAuthorizationException: Not authorized to access group: demo-consumer-1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.750 s
[INFO] Finished at: 2019-06-13T18:27:42+00:00
[INFO] Final Memory: 26M/377M
https://github.com/confluentinc/examples/blob/5.2.1-post/ccloud/acl.sh 
https://github.com/confluentinc/examples/blob/5.2.1-post/ccloud/acl.sh
https://github.com/confluentinc/examples/blob/5.2.1-post/ccloud/acl.sh
Line 315 ccloud kafka acl create --allow --service-account-id $SERVICE_ACCOUNT_ID --

https://github.com/confluentinc/examples/blob/5.2.1-post/clients/cloud/java/src/main/java/io/confluent/examples/clients/cloud/ConsumerExample.java
I changed the group.id to match the ACL
    props.put(ConsumerConfig.GROUP_ID_CONFIG, "demo-consumer-1"); CHANGED to 
 but we never saw the expected output "Successfully joined group" so acl.sh threw an error

[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:java (default-cli) on project clients-example: An exception occured while executing the Java class. null: InvocationTargetException: Not authorized to access group: demo-consumer-1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch

**Comment by ybyzek** [comment]
Resolved in #176
