### ISSUE TITLE
Cannot create multiple brokers on kafka cluster

### ISSUE THREAD

**Issue by djamel-benamara** [confluentinc/examples#214]
So I created a java app with kafka and use docker-compose.
In my .yml I launch a zookeeper server and 3 brokers. The problem is that even with one broker, It doesn't work if the port is not 9092. the error is "[AdminClient clientId=adminclient-1] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.".
So I can't create multiple brokers because it seems to listen on port 9092 as the erro says.
Here is how a broker is declared in the yml file.
kafka-1:
    image: confluentinc/cp-kafka:5.2.1
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

**Comment by ybyzek** [comment]
@djamel-benamara here's an example with a broker configured to listen to a port that is not 9092: https://github.com/confluentinc/cp-demo/blob/5.3.0-post/docker-compose.yml#L90

If you have further questions, feel free to ask in Confluent's Community Slack for faster response: https://launchpass.com/confluentcommunity
