### ISSUE TITLE
RBAC sample code error

### ISSUE THREAD

**Issue by manthak** [confluentinc/examples#220]
Downloaded the sample security code trying to run the sample code and having the following error

"kafka failed to log into your metadata server. please check all parameters and run again"

    only, NOT for production usage. https://docs.confluent.io/current/cli/index.html

Using CONFLUENT_CURRENT: /tmp/confluent.daFfsIy0
zookeeper is already running. Try restarting if needed
kafka is already running. Try restarting if needed
Sogin /apps/kafka/confluent-5.3.0/etc/kafka/server.properties /tmp/original_configs/server.properties ../delta_configs/server.properties.delta
Sleeping 5 seconds before login
Sleeping 5 seconds before login

# Logina http://localhost:8090   mds
./rbac_lib.sh: line 54: expect: command not found

Failed to log into your Metadata Server.  Please check all parameters and run again
[root@ftc-lbkfkdv204 scripts]#

**Comment by ybyzek** [comment]
@manthak 

> ./rbac_lib.sh: line 54: expect: command not found

indicates that `expect` is required for this script to work.  Please install `expect` and try again.

Meanwhile, I'll file a jira to add a preflight check that `expect` is installed.

**Comment by ybyzek** [comment]
PR submitted: https://github.com/confluentinc/examples/pull/253
