### ISSUE TITLE
RBAC Docker Image 

### ISSUE THREAD

**Issue by vschandra** [confluentinc/examples#230]
I am getting following when I ran /examples/security/rbac/rbac-docker/confluent-start.sh file 

Pulling zookeeper (368821881613.dkr.ecr.us-west-2.amazonaws.com/confluentinc/cp-zookeeper:5.3.x-latest)...
ERROR: Get https://368821881613.dkr.ecr.us-west-2.amazonaws.com/v2/confluentinc/cp-zookeeper/manifests/5.3.x-latest: no basic auth credentials

**Comment by ybyzek** [comment]
@vschandra -- as described in https://github.com/confluentinc/examples/blob/5.3.0-post/security/rbac/rbac-docker/README.md#image-versions , the image name is formatted as 

https://github.com/confluentinc/examples/blob/5.3.0-post/security/rbac/rbac-docker/docker-compose.yml#L5

To resolve, please update your `PREFIX` and `TAG` env variables.
