### ISSUE TITLE
Clickstream demo doesn't work - schema inference

### ISSUE THREAD

**Issue by rmoff** [confluentinc/examples#26]
```
ksql> run script './ksql/ksql-clickstream-demo/demo/clickstream-schema.sql';
io.confluent.ksql.parser.exception.ParseFailedException: Exception while processing statements :Source CLICKSTREAM does not exist.
ksql>
```

This looks to be related to https://github.com/confluentinc/ksql/issues/1320 and https://github.com/confluentinc/ksql/pull/1599 -- KSQL is aborting because it can't find an object even though it is created as part of the script.

**Comment by rmoff** [comment]
Need to check this against https://github.com/confluentinc/ksql/tree/master/ksql-clickstream-demo and see if that works.

**Comment by big-andy-coates** [comment]
I've checked [this version](https://github.com/confluentinc/ksql/pull/1897) and it seems to work fine, once I've applied either [this change](https://github.com/confluentinc/ksql/pull/1898) to the KSQL version, or [this change](https://github.com/confluentinc/quickstart-demos/pull/41) to this repos version of the script.

**Comment by hisgarden** [comment]
on line#67 of './ksql/ksql-clickstream-demo/demo/clickstream-schema.sql'

```
ksql> CREATE TABLE WEB_USERS (user_id int, registered_At long, username varchar, first_name varchar, last_name varchar, city varchar, level varchar) with (key='user_id', kafka_topic = 'clickstream_users', value_format = 'json');
Invalid primitive column type: LONG
```

changed registered_At long to registered_At bigint fix this error

**Comment by rmoff** [comment]
@hisgarden Thanks for reporting. This was [fixed recently](https://github.com/confluentinc/ksql/commit/9609084ce225936be3fbba6da254e1fcf1ed7c86#diff-a5f0f3f5a6f3697730f63f284069fd33R58) in `5.0.0-post` of the KSQL repo, but was missed from this one. I've raised internal ticket DEVX-414 to track this (and hopefully unify the code base).  /cc @ybyzek

**Comment by rmoff** [comment]
#41 still unmerged; re-opening to track

**Comment by ybyzek** [comment]
DEVX-414 is resolved and clickstream demo has been validated on `5.5.0-post`, so closing this GH issue.   If there are any issues with this demo, please open a new GH issue.
