### ISSUE TITLE
Multi Region Image Pull Error

### ISSUE THREAD

**Issue by AdheipSingh** [confluentinc/examples#358]
Tried this on master branch as well as 5.4.x.  Not able to get the stack up.
```
sudo docker-compose up -d
Pulling zookeeper-west (confluentinc/cp-zookeeper:5.4.0-SNAPSHOT)...
ERROR: manifest for confluentinc/cp-zookeeper:5.4.0-SNAPSHOT not found
```

**Comment by ybyzek** [comment]
@AdheipSingh as we are prepping for 5.4 GA, tooling automation bumped all Docker image references to `5.4.0-SNAPSHOT`, which is unfortunately not available to external users.  Sorry about that.  To get this to work, please use Docker image tag `5.4.0-beta1-2` instead, e.g. `confluentinc/cp-server:5.4.0-beta1-2`

**Comment by AdheipSingh** [comment]
@ybyzek thanks for the update.
