### ISSUE TITLE
writting new data to a topic?

### ISSUE THREAD

**Issue by dmead** [confluentinc/examples#39]
maybe it's escaping me, but how do you write new data to a topic? spark has the idea of receivers, so i expected to find some analog to that here.

**Comment by ewencp** [comment]
@dmead In Kafka you use Producers to write data to topics. This repository has a [producer example](https://github.com/confluentinc/examples/tree/master/kafka-clients/producer) and our [clients documentation](http://docs.confluent.io/3.0.0/clients/index.html) explains both the producer and consumer.
