### ISSUE TITLE
Client Support for Observers

### ISSUE THREAD

**Issue by AdheipSingh** [confluentinc/examples#401]
Currently i am using this command to create a topic in a specific region using the replica placement flag. 
```
kafka-topics  --create         --bootstrap-server mybroker:9092 --topic single-region         --partitions 1         --replica-placement topic-config/multi-region-async.json         --config min.insync.replicas=1
```
Can i leverage the same in my  producer api, which clients support this option.

**Comment by jsancio** [comment]
Hi @AdheipSingh,

The `kafka-topics` command controls how many topic partitions are created and how brokers/replicas get assigned to those topic partitions. After the topic partitions get created and after the Kafka Controller elects a leader for each topic partition, the Kafka producer will always produce messages to the topic partition leaders.

**Comment by jsancio** [comment]
@AdheipSingh, if you are interested in creating a topic using the Java `Admin` client, you need to specify the constraint as an configuration option. For example, in Scala:

```scala
val topicName = "topic-name"
val partitions = Optional.of(1)
val replication = Optional.empty()
val newTopic = new NewTopic(topicName, partitions, replication)
val replicaPlacementJson = """{"version": "1", "replicas": ..., "observers": ...}"""
newTopic.configs(
  Map(ConfluentTopicConfig.TOPIC_PLACEMENT_CONSTRAINTS_CONFIG -> replicaPlacementJson).asJava
)

val createResult = adminClient.createTopics(Collections.singleton(newTopic))
createResult.all().get()
```

We will have Java Docs describing this once 5.4 is released.

**Comment by AdheipSingh** [comment]
@jsancio looks good, thanks for the update.
