### ISSUE TITLE
Running "make" in Ubuntu for Producing messages to Confluent-Kafka from C Client

### ISSUE THREAD

**Issue by rajnikhil17** [confluentinc/examples#416]
I want to try producing messages to a confluent-kafka topic from librdkafka,
I have cloned the git repository

I am getting the error while runrning "make"

~/examples/clients/cloud/c$ make
cc   consumer.c common.c json.c -o consumer -lrdkafka -lm
common.c: In function ‘create_topic’:
common.c:134:9: error: unknown type name ‘rd_kafka_NewTopic_t’; did you mean ‘rd_kafka_topic_t’?
         rd_kafka_NewTopic_t *newt;
         ^~~~~~~~~~~~~~~~~~~
         rd_kafka_topic_t
common.c:138:15: error: unknown type name ‘rd_kafka_CreateTopics_result_t’
         const rd_kafka_CreateTopics_result_t *res;
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
common.c:139:15: error: unknown type name ‘rd_kafka_topic_result_t’
         const rd_kafka_topic_result_t **restopics;
               ^~~~~~~~~~~~~~~~~~~~~~~
common.c:145:16: warning: implicit declaration of function ‘rd_kafka_NewTopic_new’; did you mean ‘rd_kafka_topic_new’? [-Wimplicit-function-declaration]
         newt = rd_kafka_NewTopic_new(topic, num_partitions, replication_factor,
                ^~~~~~~~~~~~~~~~~~~~~
                rd_kafka_topic_new
common.c:145:14: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
         newt = rd_kafka_NewTopic_new(topic, num_partitions, replication_factor,
              ^
common.c:157:9: warning: implicit declaration of function ‘rd_kafka_CreateTopics’; did you mean ‘rd_kafka_queue_poll’? [-Wimplicit-function-declaration]
         rd_kafka_CreateTopics(rk, &newt, 1, NULL, queue);
         ^~~~~~~~~~~~~~~~~~~~~
         rd_kafka_queue_poll
common.c:159:9: warning: implicit declaration of function ‘rd_kafka_NewTopic_destroy’; did you mean ‘rd_kafka_topic_destroy’? [-Wimplicit-function-declaration]
         rd_kafka_NewTopic_destroy(newt);
         ^~~~~~~~~~~~~~~~~~~~~~~~~
         rd_kafka_topic_destroy
common.c:181:15: warning: implicit declaration of function ‘rd_kafka_event_CreateTopics_result’; did you mean ‘rd_kafka_event_topic_partition’? [-Wimplicit-function-declaration]
         res = rd_kafka_event_CreateTopics_result(rkev);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
               rd_kafka_event_topic_partition
common.c:181:13: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
         res = rd_kafka_event_CreateTopics_result(rkev);
             ^
common.c:186:21: warning: implicit declaration of function ‘rd_kafka_CreateTopics_result_topics’; did you mean ‘rd_kafka_event_topic_partition’? [-Wimplicit-function-declaration]
         restopics = rd_kafka_CreateTopics_result_topics(res, &restopic_cnt);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                     rd_kafka_event_topic_partition
common.c:186:19: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
         restopics = rd_kafka_CreateTopics_result_topics(res, &restopic_cnt);
                   ^
common.c:189:13: warning: implicit declaration of function ‘rd_kafka_topic_result_error’; did you mean ‘rd_kafka_topic_destroy’? [-Wimplicit-function-declaration]
         if (rd_kafka_topic_result_error(restopics[0]) ==
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
             rd_kafka_topic_destroy
common.c:192:25: warning: implicit declaration of function ‘rd_kafka_topic_result_name’; did you mean ‘rd_kafka_topic_name’? [-Wimplicit-function-declaration]
                         rd_kafka_topic_result_name(restopics[0]));
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
                         rd_kafka_topic_name
common.c:191:41: warning: format ‘%s’ expects argument of type ‘char *’, but argument 3 has type ‘int’ [-Wformat=]
                 fprintf(stderr, "Topic %s already exists\n",
                                        ~^
                                        %d
                         rd_kafka_topic_result_name(restopics[0]));
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
common.c:196:25: warning: implicit declaration of function ‘rd_kafka_topic_result_error_string’; did you mean ‘rd_kafka_event_error_string’? [-Wimplicit-function-declaration]
                         rd_kafka_topic_result_error_string(restopics[0]));
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                         rd_kafka_event_error_string
common.c:194:58: warning: format ‘%s’ expects argument of type ‘char *’, but argument 3 has type ‘int’ [-Wformat=]
                 fprintf(stderr, "Failed to create topic %s: %s\n",
                                                         ~^
                                                         %d
                         rd_kafka_topic_result_name(restopics[0]),
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
common.c:194:62: warning: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Wformat=]
                 fprintf(stderr, "Failed to create topic %s: %s\n",
                                                             ~^
                                                             %d
common.c:196:25:
                         rd_kafka_topic_result_error_string(restopics[0]));
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
common.c:199:41: warning: format ‘%s’ expects argument of type ‘char *’, but argument 3 has type ‘int’ [-Wformat=]
                 fprintf(stderr, "Topic %s successfully created\n",
                                        ~^
                                        %d
                         rd_kafka_topic_result_name(restopics[0]));
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Makefile:10: recipe for target 'consumer' failed
make: *** [consumer] Error 1

**Comment by rnpridgeon** [comment]
This looks like you installed librdkafka from the public apt-repository as opposed to Confluent's. Please follow the instructions in the readme to configure your apt-repository to point at Confluent's and try again. 

https://github.com/edenhill/librdkafka/blob/master/README.md#installing-prebuilt-packages

```
$wget -qO - https://packages.confluent.io/deb/5.4/archive.key | apt-key add -
$add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/5.4 stable main
$apt-get update
$apt install librdkafka-dev

$make
cc   consumer.c common.c json.c -o consumer -lrdkafka -lm
cc   producer.c common.c json.c -o producer -lrdkafka -lm

```

**Comment by rajnikhil17** [comment]
@rnpridgeon Thank You, That Worked

**Comment by edenhill** [comment]
We've improved the error message when the librdkafka version is too old.

Thanks for filing this issue!
