### ISSUE TITLE
0.10.0.1-SNAPSHOT not available

### ISSUE THREAD

**Issue by skyahead** [confluentinc/examples#47]
With today's (Jul 21) build, I am not able to build it anymore. Seems the snapshot files are missing from confluent's maven?

$ mvn clean compile
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building streams-examples 3.1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://packages.confluent.io/maven/org/apache/kafka/kafka-clients/0.10.1.0-SNAPSHOT/maven-metadata.xml
Downloading: http://packages.confluent.io/maven/org/apache/kafka/kafka-clients/0.10.1.0-SNAPSHOT/kafka-clients-0.10.1.0-SNAPSHOT.pom
[WARNING] The POM for org.apache.kafka:kafka-clients:jar:0.10.1.0-SNAPSHOT is missing, no dependency information available
Downloading: http://packages.confluent.io/maven/org/apache/kafka/kafka-streams/0.10.1.0-SNAPSHOT/maven-metadata.xml
Downloading: http://packages.confluent.io/maven/org/apache/kafka/kafka-streams/0.10.1.0-SNAPSHOT/kafka-streams-0.10.1.0-SNAPSHOT.pom
[WARNING] The POM for org.apache.kafka:kafka-streams:jar:0.10.1.0-SNAPSHOT is missing, no dependency information available
Downloading: http://packages.confluent.io/maven/org/apache/kafka/kafka_2.11/0.10.1.0-SNAPSHOT/maven-metadata.xml
Downloading: http://packages.confluent.io/maven/org/apache/kafka/kafka_2.11/0.10.1.0-SNAPSHOT/kafka_2.11-0.10.1.0-SNAPSHOT.pom
[WARNING] The POM for org.apache.kafka:kafka_2.11:jar:test:0.10.1.0-SNAPSHOT is missing, no dependency information available
Downloading: http://packages.confluent.io/maven/org/apache/kafka/kafka_2.11/0.10.0.0-cp1/kafka_2.11-0.10.0.0-cp1.pom
Downloaded: http://packages.confluent.io/maven/org/apache/kafka/kafka_2.11/0.10.0.0-cp1/kafka_2.11-0.10.0.0-cp1.pom (5 KB at 19.1 KB/sec)
Downloading: http://packages.confluent.io/maven/org/apache/kafka/kafka-clients/0.10.0.0-cp1/kafka-clients-0.10.0.0-cp1.pom
Downloaded: http://packages.confluent.io/maven/org/apache/kafka/kafka-clients/0.10.0.0-cp1/kafka-clients-0.10.0.0-cp1.pom (2 KB at 4.2 KB/sec)
Downloading: http://packages.confluent.io/maven/org/apache/kafka/kafka-clients/0.10.1.0-SNAPSHOT/kafka-clients-0.10.1.0-SNAPSHOT.jar
Downloading: http://packages.confluent.io/maven/org/apache/kafka/kafka-streams/0.10.1.0-SNAPSHOT/kafka-streams-0.10.1.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.464 s
[INFO] Finished at: 2016-07-21T23:03:39-04:00
[INFO] Final Memory: 11M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project streams-examples: Could not resolve dependencies for project io.confluent:streams-examples:jar:3.1.0-SNAPSHOT: The following artifacts could not be resolved: org.apache.kafka:kafka-clients:jar:0.10.1.0-SNAPSHOT, org.apache.kafka:kafka-streams:jar:0.10.1.0-SNAPSHOT: Could not find artifact org.apache.kafka:kafka-clients:jar:0.10.1.0-SNAPSHOT in confluent (http://packages.confluent.io/maven/) -> [Help 1]

**Comment by ewencp** [comment]
We don't publish snapshots to our public Maven. See https://github.com/confluentinc/examples/wiki/FAQ#when-i-try-to-compile-i-get-an-error-about-a-missing-snapshot-dependency (you probably want the kafka-0.10.0.0-cp-3.0.0 branch).
