### ISSUE TITLE
Connect example for Kafka Streams

### ISSUE THREAD

**Issue by clumsy** [confluentinc/examples#48]
I didn't find any example of working with Connect data format in kafka-streams.
More over that  - it seems impossible to work with Connect data via `Serde<GenericRecord>` because there is a number of incompatibilities.
E.g. String is converted to `Utf8` in `GenericRecord` but `Struct` expects a `String`, also Avro parser knows nothing about Connect-specific metadata, like actual `int` precision (`int8`, `int16`, etc.).

As far as I was able to understand one can/has to create a `Serde<SchemaAndValue>` that will use an `AvroConverter` that will get the data from the schema registry.

Please correct me if I'm wrong and if I'm not I can contribute an example.
Although in case I'm correct there should be `ConnectSerde<SchemaAndValue>` available somewhere - and I can contribute that too.

**Comment by cjmatta** [comment]
Hi @clumsy I have a Streams example app that uses the `SpecificAvroSerde` from the [example repo](https://github.com/confluentinc/examples/blob/3.1.x/kafka-streams/src/main/java/io/confluent/examples/streams/utils/SpecificAvroSerde.java) here: https://github.com/cjmatta/WikipediaChangesMonitor

Is this what you're looking for?

**Comment by clumsy** [comment]
Hi @cjmatta,
The example I mentioned is not for a generic/specific avro serde, but rather a Kafka Connect-specific avro format (SchemaAndValue). The one that is used by Kafka Connect plugins, for example JDBC.
With this implementation you don't need to compile avro specs, but rather use Kafka Connect schema registry.

**Comment by artemb** [comment]
Good question! I faced the same problem - data produced by Kafka Connect is not easy to work with in Kafka Streams. Seems odd as "Load with Kafka Connect, process with Kafka Streams, export with Kafka Connect" is the promoted way of building data pipelines, isn't it?

Thank you

**Comment by clumsy** [comment]
Precisely so, @artemb. I believe the project is not mature enough yet, the API changes drastically every release.
Anyone willing to use it now has to understand that certain effort has to be invested.

The feedback is not that good too. It has been almost a year since I suggested adding the example willing to contribute - there was no reply.

**Comment by miguno** [comment]
@clumsy: We just added official Avro serdes (for generic Avro + for specific Avro) for Kafka Streams, see https://github.com/confluentinc/schema-registry/pull/531.  The work on a setup for Connect/Streams, similar to what you describe here, is also in the backlog.

> The feedback is not that good too. It has been almost a year since I suggested adding the example willing to contribute - there was no reply.

Sorry that we haven't been able to be as responsive as we would have liked to!  If you are still willing to contribute, we'd definitely appreciate that and be supportive. :-)

**Comment by mjsax** [comment]
@clumsy 

> API changes drastically every release

We have the policy to do all changes in a backward compatible way now. And some API changes are required not because the API is not mature, but because we add new features that require a different API pattern to keep the user experience positive.

**Comment by clumsy** [comment]
Dear @mjsax, I don't want to start a holy war here, just sharing my experience (which I had almost a year ago).
Breaking changes seem to happen almost [every release](https://www.google.com/search?q=confluent+breaking+changes) - mostly due to Kafka, sure.

But API changes happen even for minor releases, e.g. 3.1.1:

> Kafka Streams and its API were improved and modified since the release of CP 3.0.x. Some of these changes are breaking changes that require you to update the code of your Kafka Streams applications. In this section we focus on only these breaking changes.

Do you mean that starting 3.2.0 the changes are backward-compatible?
If one does not have to refactor existing code just to pick up a few bugfixes in a minor release of the current version - that would be great!

**Comment by mjsax** [comment]
@clumsy you are absolutely right -- up to now, we did have breaking changes, but we are not doing it for future releases (note, "now" in my reply from above -- maybe it was too subtle). And I did not take any offense from your comment -- we highly appreciate any user feedback (positive or negative). Actually, we rely on negative (constructive) feedback to make it better in the future (and your feedback is constructive!).

Note, I can only speak for Streams API -- overall the project is too big and I don't have a complete overview. We are still refining the API, but we `deprecate` methods now and not remove them directly. We will still remove them eventually (no policy yet; personally I think 2 minor releases later might be a good way to handle it). For this reason, all classes/interfaces from Streams API are still tagged as `@Unstable`.

However, I want to point out that Streams API did not have any breaking changes for minor releases -- the upgrade section for `3.1.1` contains only breaking changes from `3.0.x` to `3.1.1` (that is the same section as for `3.1.0`). It's not for upgrading from `3.1.0` to `3.1.1`. We did this, to avoid that users need to go back to "old" docs if they want to upgrade from `3.0.x` -- do you think this is too confusion and we should do it differently?

**Comment by clumsy** [comment]
@mjsax got it, thanks.
Isn't 3.1.0 a [minor release](https://en.wikipedia.org/wiki/Software_versioning)? (MAJOR.MINOR.PATCH format)

**Comment by mjsax** [comment]
Oh sorry. My bad. Guess it was too late yesterday... I had bug-fix release in mind. I am sure, we will have Streams API changes in minor release in the future, too. But as mentioned, all will be backward compatible. We still need to figure out a policy for when to remove deprecated API... If you follow the mailing list, I guess we will have an open discussion about this at some point.

**Comment by miguno** [comment]
FYI: We are currently working on such an end-to-end Connect+Streams demo.  See the PR at https://github.com/confluentinc/examples/pull/120.

**Comment by miguno** [comment]
Such an example is now available in the top-level `kafka-connect-streams/` folder.

For the `3.2.x` branch, see https://github.com/confluentinc/examples/tree/3.2.x/kafka-connect-streams.

Closing this for now.  Feel free to create follow-up GH issues when/if needed.
