### ISSUE TITLE
Unicode characters support?

### ISSUE THREAD

**Issue by igorglad** [confluentinc/examples#49]
I have tried to run the WordCoundLambdaExample and it worked just fine until I have tried to push some unicode characters into the TextLinesTopic topic - the WordCoundLambdaExample just ignored those. No exception thrown or anything. Is it something wrong with my configuration?

**Comment by igorglad** [comment]
I have used the kafka-console producer from the command line and just switched to the Russian input layout. I use iTerm2 as my shell client.

**Comment by miguno** [comment]
@guozhangwang  Do you know more?

**Comment by igorglad** [comment]
let me debug it and I will let you know where the problem is

**Comment by igorglad** [comment]
When I do not use Kafka Streams, kafka works fine with unicode characters:

Producer:
$ $KAFKA_HOME/bin/kafka-console-producer --broker-list localhost:9092 --topic "TextLinesTopic"
hello world
Русское слово

Consumer:
$ $KAFKA_HOME/bin/kafka-console-consumer --from-beginning --zookeeper localhost:2181 --topic "TextLinesTopic"
hello world
русское слово

But when I try to run WordCountLambdaExample app, it skips Russian words:
Producer:

$ $KAFKA_HOME/bin/kafka-console-producer --broker-list localhost:9092 --topic "TextLinesTopic"
English words are following
Here some more English words
И теперь пошли русские слова
Again English words

$KAFKA_HOME/bin/kafka-console-consumer --topic WordsWithCountsTopic --from-beginning --zookeeper localhost:2181 --property print.key=true --property value.deserializer=org.apache.kafka.common.serialization.LongDeserializer
english	1
words	1
are	1
following	1
here	1
some	1
more	1
english	2
words	2
again	1
english	3
words	3

**Comment by dguy** [comment]
KafkaStreams works ok with unicode - it is actually `value.toLowerCase().split("\\W+")` in `WordCountLambdaExample` that is causing the issue. The split of the Russian words returns a 0 sized array. So they get dropped. If you change it to `value.toLowerCase().split("\\s+")` it works, though this won't handle non-word characters properly

**Comment by dguy** [comment]
Hi, i've just pushed a change to the examples that fixes this issue.

**Comment by miguno** [comment]
@dguy: Can you also push this change to our two `kafka-0.10.0.*` branches?

**Comment by dguy** [comment]
Yep - done.

**Comment by guozhangwang** [comment]
Thanks @dguy !!
