### ISSUE TITLE
Multiple processors belongs to either same or different group needs to be read same message from same partition of the topic.

### ISSUE THREAD

**Issue by deepakpengoria** [confluentinc/examples#54]
Problem statement : I have a topic-B which is used to contain configuration related information that's why only one partition P is sufficient. Now I want all the instances/tasks of streaming api application could read the same configuration. How can I achieve this? Is this possible through TopologyBuilder?  For your information, we write once in a week/month in topic-B to update the configuratoin. Below diagram might clear the problem statement. If you need more information, please let me know. 
![partitionmultipletask](https://cloud.githubusercontent.com/assets/19401127/17767257/e47490b8-654c-11e6-8557-9116978d7dd4.png)

**Comment by miguno** [comment]
Sorry, your question slipped under my radar @deepakpengoria.

This is not yet possible (as of Apache Kafka 0.10.0).

Moving forward what we want to add is "global" KTable / state stores, which -- in the case of configuration relation information -- should address your question.
