### ISSUE TITLE
org.apache.avro.SchemaParseException: Can't redefine: page_visit

### ISSUE THREAD

**Issue by eamocanu** [confluentinc/examples#63]
I can send the message the first time after which I get an error saying I can't use the same schema to send other messages:
org.apache.avro.SchemaParseException: Can't redefine: page_visit
If I add random character to the name in schema IO can send other messages.

How can this error be avoided?

A

**Comment by miguno** [comment]
@eamocanu There's not a lot of information in your question, so it's difficult to help you.

For example:
- To which code example are you referring to?
- Which message(s) are you sending?
- Which "same" schema are you referring to?
- What do you mean by "If I add random character to the name in schema IO can send other messages." (what is "schema IO"?)

**Comment by miguno** [comment]
Closed (inactive).  Feel free to reopen if needed.
