### ISSUE TITLE
config directories don't exist any more; kafka-topics.sh is now kafka-topics

### ISSUE THREAD

**Issue by dmatrix** [confluentinc/examples#7]
A minor fix to the README.md that reflects the current distribution of CD 1.0.1.

1. config directories no long exist. Instead the command scripts for the examples should refer to ./etc not ./config
2. kafka-topics.sh has been renamed to kafka-topics, so that reference to this script in the examples should reflect that change.

**Comment by Ishiihara** [comment]
@dmatrix Just submit a pull request #8 to address this issue. Let me know if this addresses your concern.

**Comment by dmatrix** [comment]
I guess it has been addressed. Thanks!

cheers
Jules

--
"Developers Are the New Kingmakers."
Jules Damji
dmatrix@comcast.net

**Comment by Ishiihara** [comment]
Resolved by #8
