### ISSUE TITLE
ccloud_library.sh uses hardcoded cloud provider and region for schema registry deployment

### ISSUE THREAD

**Issue by mkieboom** [confluentinc/examples#704]
The ccloud_library.sh script in the utils folder has hardcoded cloud provider (aws) and region (us) for the cloud schema registry deployment. eg:
`OUTPUT=$(ccloud schema-registry cluster enable --cloud aws --geo us -o json)`

Which should be as below as per my understanding of the code:
`OUTPUT=$(ccloud schema-registry cluster enable --cloud $SCHEMA_REGISTRY_CLOUD --geo $SCHEMA_REGISTRY_GEO -o json)`

I'll provide a pull request to fix this. Bare with me if that goes well as it has been a while since I've done that :-)

**Comment by ybyzek** [comment]
@mkieboom great catch!  Thanks for reporting and fixing 🥇

**Comment by mkieboom** [comment]
Merged.
