### ISSUE TITLE
Typo in Ruby README.md

### ISSUE THREAD

**Issue by mntlty** [confluentinc/examples#722]
There is a typo in the Ruby readme https://github.com/confluentinc/examples/blob/e797223aba195ad5d0f012807aa954610e8bde9d/clients/cloud/ruby/README.md
the config file is incorrectly named in both of the code snippets as `librdkafa.config` (missing a K)

**Comment by ybyzek** [comment]
@mntlty good catch.  Resolved by https://github.com/confluentinc/examples/commit/a728af07677214f41a52c26d49ab3e78dac0dd86
