### ISSUE TITLE
ccloud_library.sh ccloud::create_ccloud_stack throws error on CentOS 7

### ISSUE THREAD

**Issue by mkieboom** [confluentinc/examples#723]
The create_ccloud_stack function in the ccloud_library.sh works perfectly fine when running it on MacOS but fails with below error when running on Linux/CentOS 7.

```
Error: accepts 1 arg(s), received 0
Usage:
  ccloud kafka cluster use <id> [flags]

Global Flags:
  -h, --help            Show help for this command.
  -v, --verbose count   Increase verbosity (-v for warn, -vv for info, -vvv for debug, -vvvv for trace).

Kafka cluster id is empty
ERROR: Could not create cluster. Please troubleshoot
```

**Comment by ybyzek** [comment]
`ccloud_library.sh` is currently validated only on macOS, we have not yet validated it on other OS.

I'll create an internal jira to track this issue.  We either need to test on both, otherwise add documentation on the OS test coverage

**Comment by mkieboom** [comment]
Understood, thanks @ybyzek

**Comment by ybyzek** [comment]
@mkieboom thanks for reporting 👍

**Comment by ybyzek** [comment]
@mkieboom @rspurgeon is this GitHub issue resolved by https://github.com/confluentinc/examples/pull/737 ?

**Comment by rspurgeon** [comment]
I believe so, however, I did not personally validate this change on a Linux system, instead verified the code change on MacOS and leaned on @mkieboom to verify on Linux.  We can close this AFAIK unless you'd like me to add to my list a validation on Linux.

**Comment by Lay3r8** [comment]
> `ccloud_library.sh` is currently validated only on macOS, we have not yet validated it on other OS.
> 
> I'll create an internal jira to track this issue. We either need to test on both, otherwise add documentation on the OS test coverage

May I kindly suggest that you guys add a prerequisite section on your docs and tutorials (like this one: https://kafka-tutorials.confluent.io/ccloud-produce-consume/kafka.html) to avoid people trying for hours to do something that is doomed to fail because they don't have the correct OS?

**Comment by ybyzek** [comment]
@Lay3r8 

1. There is an existing prerequisite section in the docs (https://docs.confluent.io/current/tutorials/examples/ccloud/docs/ccloud-stack.html) but it omits mention of OS.  I filed an internal jira to track adding this in (DEVX-2191) -- UPDATE: now documented in the [docs](https://docs.confluent.io/current/tutorials/examples/ccloud/docs/ccloud-stack.html?utm_source=github&utm_medium=demo&utm_campaign=ch.examples_type.community_content.clients-ccloud#prerequisites
)

2. I don't think non-macOS are _doomed_ to fail, just that they haven't necessarily been validated on an on-going basis.  We still want to surface issues with other OS and try to resolve them best effort, as done with https://github.com/confluentinc/examples/pull/737/files

3. Did you encounter a problem with `ccloud-stack`?  If so, please share the error in a _new_ GitHub issue and we can track there.

Thanks!
