### ISSUE TITLE
join of Kstreams

### ISSUE THREAD

**Issue by mazorigal** [confluentinc/examples#74]
Hi,

I would like to understand the implementation used for join between Kstreams.
Is the implementation a simple hash join that builds a hash table on one side (until the window is full) and buffers data on the other input. Once the window is complete, the buffered data is joined against the window ? 

Also, is the restriction for having same number of partitions and partition on the same key applies also for the join between Kstream and a KTable ? (I assume that yes, but want to be sure)

In case when one of the streams have much higher volumes of data (for example click stream and location of the user stream), the click stream should have more topic partitions then the user location stream, how streams joins can be achieved in such case ? would you still force same number of partitions for each topic ?

Thanks,

**Comment by mjsax** [comment]
Kafka Streams uses hash-based join algorithms. The detailed semantics depend on the type of join you are doing, ie, KStream-KStream, KStream-KTable, or KTable-KTable (for details see https://cwiki.apache.org/confluence/display/KAFKA/KIP-77%3A+Improve+Kafka+Streams+Join+Semantics). Some of those join do use windows; for those, the join in computed continuously, ie, there is no wait until a window is closed (in Kafka Streams, windows are never closed in general) but each time a records arrives, it is inserted in its own stream's window and a lookup in the other stream's window is done to compute results.

Yes, joining two streams (of any kind) requires both to be partitioned on the join key using the same number of partitions. Thus, you would need to over partition the lower rate stream with the larger number of partitions from the high rate stream. This repartitioning will happen automatically in the next release of Kafka 0.10.1.0 (should be release this or next week); currently, you need to create a topic manually with the correct number of partitions before you start your Kafka Streams application and repartition before the join using `through(...)`.

See CP docs for more details: http://docs.confluent.io/current/streams/developer-guide.html#joining-streams

**Comment by mazorigal** [comment]
the example of kstreams joins, on the link you have provided, indeed help to understand the different types of join semantics, however  one thing is still not so much clear to me.
The state window for each stream (or only for the left stream) is not limited by time at all ? the state would be updated continuously ? or the state window is reseted on a specific time intervals ?
For left joins, if the record in the right streams arrives after the corresponding record in the left stream => does it mean that those two could never be joined ? 

Regarding the repartition:
is the repartition of the low rate topic based on the high rate topic, would not lead to a wrong resources utilization of the kafka cluster ? I mean, what for then the need to optimize (http://www.confluent.io/blog/how-to-choose-the-number-of-topicspartitions-in-a-kafka-cluster) the number of partitions per topic if eventually the low rate would be any way repartitioned based on the topic with the higher number of partitions ?

**Comment by mjsax** [comment]
About windows: Kafka Streams will keep *all* windows open in parallel -- windows are only deleted after their retention time passed. You can set retention time via `Windows#until(...)`. Keeping all windows open all the time has the advantage that late arriving out-of-order data can be processed easily. (see http://docs.confluent.io/3.0.1/streams/concepts.html#windowing)

> For left joins, if the record in the right streams arrives after the corresponding record in the left stream => does it mean that those two could never be joined ?

Currently, yes. However, KIP-77 will fix this (not for KStream-KTable joins though).

About repartitioning: The blog post you cite was written before Kafka Streams and does not apply to Kafka Streams directly. The guideline is still valid and helpful, but using Kafka Streams changes the picture and you cannot apply it without considering Kafka Streams architecture. So yes, in this case resource utilization might not be optimal and this is a valid concern. I will put it into general Kafka Streams discussion -- maybe we can improve on this in the future.

**Comment by mazorigal** [comment]
so if I understand your answers and docs in case window size is 10 minutes and retention time 25 minutes, then for some stream A, first state window will start at t1 and after 24 minutes would be 3 open windows ? and after 26 minutes would be 2 open windows ?
in case of join between two streams, how kafka-streams know in which window state to do the lookup ? (is it depends on the window start_time / end_time, which is somehow part of the window id ? )
wouldn't keeping all the windows open all the time affect strongly on the resources consumption - especially memory ?

regarding  repartition, then I guess it is better to create the low rate stream from advance with same number of partitions as the high rate stream, otherwise other teams or use cases that need to have the same join, would actually create multiple topics (for same thing) as a result from the repartition during the join itself ?

**Comment by miguno** [comment]
> wouldn't keeping all the windows open all the time affect strongly on the resources consumption - especially memory ?

It does impact resource consumption (of course -- your processing "brain" needs to remember more things).  But memory-wise it is not that problematic actually: state is by default not managed in-memory but through local RocksDB instances, i.e. off-heap and on-disk.  Also, all the windows are not kept open all the time -- windows are definitely closed/discarded once they have exceeded their retention time.

> regarding repartition, then I guess it is better to create the low rate stream from advance with same number of partitions as the high rate stream, otherwise other teams or use cases that need to have the same join, would actually create multiple topics (for same thing) as a result from the repartition during the join itself ?

You can do that, i.e. `partitions = max(low_rate_partitions, high_rate_partitions)`, and it might be a good idea in your case (hard to tell from afar), but you don't necessarily need to.  That said, in general it doesn't hurt to "over-partition" your topics -- so go with your idea if it looks promising to you.

**Comment by mjsax** [comment]
Want to add to @miguno answer.

Yes, you number of windows you describe is correct for you example. And yes, we keep the window start/end time for each window to do the lookup.

**Comment by mjsax** [comment]
@mazorigal Can we close this? Or do you have more questions?

**Comment by mazorigal** [comment]
@mjsax thanks a lot for the answers.
You can close it.
