### ISSUE TITLE
external services

### ISSUE THREAD

**Issue by mazorigal** [confluentinc/examples#77]
Hi,

after reading the kafka streams docs, my understand is that kafka streams support async operations by means of creating new topics and therefore one should be careful with blocking operations such as calling DB services, since that can slow down the stream. What happens in case of async  DB service that return Future (scala in my case) ? would kafka streams wait until the Future is completed ? would it send the Future down the stream ? Do I need by myself to wait for the Future complete (if yes, then its same as writing non async blocking code )

What would be best practice for cases when I would like (for example) to enrich the stream data using some external data source (such as cassandra, elasticseach, or maybe even other REST service) ?

Thanks,

**Comment by mjsax** [comment]
Dealing with future would break fault-tolerance guarantees (or you need to take into account). Kafka Streams does commit its progress in regular intervals, and on commit, processing of all in-flight records will be finished, and all pending output records will be written (also all state will be flushed). Thus, if you have an future that is not finished yet during a commit, you might loose this data when an error occurs after the commit and before the future returns.

If you want to enrich your stream with external data, the best way is to leverage Kafka Connect to write this data into a topic and read the topic as a `KTable`. Than, you can do a KStream-KTable join to lookup the data in the `KTable` and enrich your `KStream` records.

**Comment by mazorigal** [comment]
>  Kafka Streams does commit its progress in regular intervals, and on commit, processing of all in-flight records will be finished
What happens if there is still some recored for which the process is not done ?

So if I understand your answer correct, I should not use kafka-streams with any asnyc Libary (which returns Futures) or block somehow the Future by myself until it is completed ?

Using KTable is not always possible and in my opinion could be in some use cases cumbersome.
not always I can control the source stream to the persistence layer in order to stream the log change to kafka topic (in order to create the Ktable), some times the persistence layer not allowed to be accessed directly and the only way to use it is via some REST API exposed by the responsible team for that storage.
But even in cases where I can fully control the log change of some persistence layer, it can still be quite hard to make sure that the Ktable is fully sync with the "real source of true".
What happens if due to some issues, the storage stop submitting change logs to the kafka topic ? (then joining with new incoming data my result in not updated enrichment)
What happens in the followinf case:  assuming that kafka topic retention policy is set to 30 days and for some record in the persistence layer last change log (update of the record) was 35 days ago. What will happen in case of rebalancing or some failure that requires the Ktable reconstruct ? (the reconstruct would be done from the Kktable change log internal topic, but that topic have only change logs in the last 30 days)

**Comment by mjsax** [comment]
>>  Kafka Streams does commit its progress in regular intervals, and on commit, processing of all in-flight records will be finished
>
>What happens if there is still some recored for which the process is not done ?

As long as not error or rebalance occurs, nothing happens. But if an error or rebalance occurs not processed records might get lost and processing for them might not complete.

> So if I understand your answer correct, I should not use kafka-streams with any async Lib (which returns Futures) or block somehow the Future by myself until it is completed ?

Yes. On commit, you should block and wait until all futures complete. This requires the usage of Processor API. If you use DSL, commits are handles automatically under the hood and you cannot hook into them.

About `KTable`: I understand the problem. Just adding a few thought.

> some times the persistence layer not allowed to be accessed directly and the only way to use it is via some REST AP

You could use Kafka Connect to regularly pull REST API to get latest updates. Not sure if there is a connector for this already, but you could build your own.

> What happens if due to some issues, the storage stop submitting change logs to the kafka topic ? (then joining with new incoming data my result in not updated enrichment)

Well. That is a general issue. What happens ifs you external system is down and no REST call will be answered? Your application might have stall futures or block (and eventually time out and fail). It seems more stable, to decouple data import from external systems into Kafka (via Connect) from your actual application. In case the external system goes down, you application is not *directly* effected. And when the external system goes online again, Kafka Streams will process older data first. Thus, it will replay the updated to KTable faster than ongoing record stream processing. Of course, in between you might have a state that is not up-to-date and it depend on you application if you can tolerate this or not. It's a tradeoff between a "correct" app (that might crash is external system is down) and a "correct enough" but stable running app.

> the reconstruct would be done from the Kktable change log internal topic, but that topic have only change logs for the last 30 days)

Streams changelog topics do not use retention time policy but are compacted topics. Thus, it is guaranteed that each latest record for each key in never deleted.

**Comment by mazorigal** [comment]
Thanks for the answers.
I would be happy to get few more clarifications.

> You could use Kafka Connect to regularly pull REST API to get latest updates. Not sure if there is a connector for this already, but you could build your own.

not so much sure how that can be managed. If for example the REST expose N items in some storage layer, in order to pull the updated status of the items each T time, you need to call the REST api for each item ID, that by itself can be expensive and sometimes limited if the REST have some kind of requests per minute limit.

Regarding the case when REST is down, not sure that I understand why decouple data import from external systems into Kafka is better approach. In case the REST is down, the topic consumption (stream) can be also stopped and restored once the REST is back, in that case the events consumption will be also restored from the last offset.

Thanks,

**Comment by mjsax** [comment]
> not so much sure how that can be managed. If for example the REST expose N items in some storage layer, in order to pull the updated status of the items each T time, you need to call the REST api for each item ID, that by itself can be expensive and sometimes limited if the REST have some kind of requests per minute limit.

Understood. I guess it depends on you use case and lookup semantics. The idea of my suggestion was to pull updates actively -- but this might not be possible if you REST does not offer something like this (you cannot know which values did get updated, before you poll for any).

> Regarding the case when REST is down, not sure that I understand why decouple data import from external systems into Kafka is better approach. In case the REST is down, the topic consumption (stream) can be also stopped and restored once the REST is back, in that case the events consumption will be also restored from the last offset.

This also depends on you use case. The idea was, to pull all data from your REST service into Kafka  and operate (on maybe outdate) data if REST is down and new updates are not forwarded to Kafka. (Using Kafka Connect you would actively pull the REST api for updates.) Of course, if you cannot compute meaningful results on old data and want to stop your Streams application if REST is down, decoupling both does not give you any advantage.
