### ISSUE TITLE
Confluent cloud | Java Avro Serialization | junk characters in value | 

### ISSUE THREAD

**Issue by shivakumarss** [confluentinc/examples#780]
Hello All,

I am trying with basic Avro publisher in java which is available in examples 
https://github.com/confluentinc/examples/blob/5.5.1-post/clients/avro/src/main/java/io/confluent/examples/clients/basicavro/ProducerExample.java

- I was successfully able to publish in self managed confluent cloud in my local machine ( macOS ) and in machine available in GCP ( Self managed confluent binaries ) 

<img width="507" alt="Screenshot 2020-09-10 at 2 03 48 PM" src="https://user-images.githubusercontent.com/32130187/92702157-7e59fc00-f36e-11ea-9c53-7fafc977d2c6.png">

**The same was tried it confluent cloud** 

- I have a confluent cloud access, where i am trying with this same example but it is showing junk characters in value.
<img width="535" alt="Screenshot 2020-09-10 at 2 06 48 PM" src="https://user-images.githubusercontent.com/32130187/92702509-e7417400-f36e-11ea-87a7-bfa8da8644b5.png">

Steps carried out in confluent cloud 
1.  Manually created a topic by name `transactions`
2. Configuration file was created with following entries
<img width="1202" alt="Screenshot 2020-09-10 at 2 11 09 PM" src="https://user-images.githubusercontent.com/32130187/92703161-9d0cc280-f36f-11ea-97da-d3f406593dfb.png">
3. Ran the java application by passing the absolute file path configuration.
4. I am able to see the schema is also set in confluent cloud.
<img width="973" alt="Screenshot 2020-09-10 at 2 14 24 PM" src="https://user-images.githubusercontent.com/32130187/92703642-ff65c300-f36f-11ea-95ab-df3771039406.png">

Could any of you help me over here as what is missing.

**Comment by ybyzek** [comment]
@shivakumarss it is a current limitation with the UI.  However, running a consumer via CLI (e.g. https://docs.confluent.io/current/tutorials/examples/clients/docs/ccloud.html#consume-avro-records) should deserialize the data correctly.

**Comment by shivakumarss** [comment]
Thank you very much @ybyzek . data looks fine after consumption . It turned out to be UI bug in confluent cloud.

**Comment by shivakumarss** [comment]
Closing this ticket.
