### ISSUE TITLE
Change operator to $(GKE_BASE_KUBECTL_NAMESPACE) in common Makefile

### ISSUE THREAD

**Issue by DorianMaliszewski** [confluentinc/examples#782]
Hi,

Just to notify that in `examples/common/Makefile` file on the command `wait-for-zookeeper` you put `-n operator` instead of `-n $(GKE_BASE_KUBECTL_NAMESPACE)` like in the other deployment.

Thank you for this examples it helped me a lot :smile:

**Comment by DorianMaliszewski** [comment]
Sorry didn't be accurate :
Line 98 : `examples/common/Makefile`

`source $(COMMON_MKFILE_DIR)bin/retry.sh; retry 15 kubectl --context $(KUBECTL_CONTEXT) -n operator get sts zookeeper`
To
`source $(COMMON_MKFILE_DIR)bin/retry.sh; retry 15 kubectl --context $(KUBECTL_CONTEXT) -n $(KUBECTL_NAMESPACE) get sts zookeeper`

Thanks,

**Comment by rspurgeon** [comment]
Thank you very much @DorianMaliszewski , please see the PR I've opened to address this #783, feel free to review (if GitHub will let you)
