### ISSUE TITLE
kafka-streams Processor API: two parents forwarding different types

### ISSUE THREAD

**Issue by mdemierre** [confluentinc/examples#79]
I don't know if this is the right place to ask this question, but I'm wondering how to build a Processor implementation that can process data coming from two parents which produce messages of different types.

I have two sources:

- source-events -> (String, MyEvent)
- source-rules -> (String, MyRoutingRule)

Now I want to build a `EventRouterProcessor` processor that will receive both types of messages (events and rules), keep a state with the rules, and process incoming events according to these rules.

The topology would be something like:

```java
topologyBuilder
    // Source producing <String, MyEvent>
    .addSource("source-events", stringSerde.deserializer(), eventSerde.deserializer(), eventsTopic
    // Source producing <String, MyRoutingRule>
    .addSource("source-rules", stringSerde.deserializer(), ruleSerde.deserializer(), rulesTopic)

     // Processor for the two types <String, MyEvent>, <String, MyRoutingRule>
    .addProcessor("router", () -> new EventRouterProcessor(), "source-events", "source-rules")
    .addStateStore(ruleStateStore, "router")

     // Output of the processor <String, MyEvent> (or some other result, it does't matter for my question)
    .addSink("sink-routedEvents", routedEventsTopic, stringSerde.serializer(), eventSerde.serializer(), "router");
```

How should I implement the `EventRouterProcessor` processor? I could make it implement `Processor<String, Object>` but is there another cleaner and type-safe way? I'm basically looking for something like [`CoFlatMap`](https://ci.apache.org/projects/flink/flink-docs-master/api/java/org/apache/flink/streaming/api/functions/co/CoMapFunction.html) in Apache Flink, which would essentially have two `process` methods.

**Comment by mjsax** [comment]
Processor API does not offer anything like CoFlatMap. Conceptually, it receives a single input stream. Thus, if you merge two streams with different types `Processor<String, Object>` is one way to go. As an alternative, you would introduce a wrapping type, like
```
class TypeWrapper { // kept simple for brevity
    public MyEvent event = null;
    public MyRoutingRule routingRule = null:
}
````
and map source-event and source-rules accordingly (ie, each instance of TypeWrapper has always only one member set while the other is null). Thus, you can use `Processor<String, TypeWrapper>` instead of using `Object`. It will give you type safety, but you will still need to have two code passes is the processor itself to distinguish both original types.

**Comment by miguno** [comment]
@mdemierre:

> I don't know if this is the right place to ask this question, but I'm wondering how to build a Processor implementation that can process data coming from two parents which produce messages of different types.

Since you asked:  The best places to ask is such questions is typically the kafka-user mailing list (http://kafka.apache.org/contact) or the Confluent Platform mailing list (https://groups.google.com/forum/?pli=1#!forum/confluent-platform).

**Comment by mdemierre** [comment]
@mjsax Thanks, that's a good middleground, I'll use this for now. This kind of thing seems to be needed when joining two streams with some custom logic. In my case, it was about keeping the `MyRoutingRule` objects and using them to process the incoming events. In that kind of case where there is no direct key mapping between the two streams, I can't use the Streams API with KTable and KStream. I found no example nor documentation for that kind of operation. Maybe some examples for the Processor API should be added in the repository, including this use case.

@miguno Okay, I'll use the mailing lists next time. Sorry I asked at the wrong place. The wording on the README for the 3.0.1 branch was a bit confusing ("Where to get help"), I see that it has be removed. Maybe replace it with links to the mailing lists? I guess a gitter room for Kafka Streams would be good to have as well, but I don't know if the Apache Foundation uses those.

**Comment by miguno** [comment]
@mdemierre:

> @miguno Okay, I'll use the mailing lists next time. Sorry I asked at the wrong place.

No problem!  I just let you know in case you have further questions, as the mailing list has more eyeballs to look at your questions. :-)

> The wording on the README for the 3.0.1 branch was a bit confusing ("Where to get help"), I see that it has be removed.

Oh, that's actually a mistake.  I'll add the "Where to get help" section again.


Maybe replace it with links to the mailing lists? I guess a gitter room for Kafka Streams would be good to have as well, but I don't know if the Apache Foundation uses those.

**Comment by miguno** [comment]
@mdemierre:

> @mjsax Thanks, that's a good middleground, I'll use this for now. This kind of thing seems to be needed when joining two streams with some custom logic. In my case, it was about keeping the MyRoutingRule objects and using them to process the incoming events.

Btw, we are also working on supporting "global" tables/state.  You could use such global state to broadcast your full routing rules to each processor instance (i.e. instances of the same processor but running on different machines), and then do your routing/processing decisions based on this information.  Would that help in your case?

**Comment by mdemierre** [comment]
@miguno Yes, it would fit perfectly. I stumbled upon #54 talking about the same problem when looking for a solution.

I actually need something similar for the project I'm working on. It is an event processing platform with active rules, where users can dynamically create rules via a GUI or directly through a REST API. These rules are deployed and applied to incoming events. Things like: "if three temperature events with >30°C are received in a minute for the same room, send an email". The difficult part is that they are dynamically added and removed. What I do in Kafka Streams is one topology receiving the rules, which in turn creates one topology (`KStreams` instance) for each incoming rule. Since the application can be replicated, rules need to arrive to all instances so they are deployed everywhere.

The "hack" I'm using now:

- Rules arrive through a `rules-deployment` topic, with 1 partition
- Events arrive through a `events` topic with N partitions
- Instances of the main application (the static topology receiving rules) each have a different Application ID (so it's like a broadcast when reading `rules-deployment`)
- Rule topologies are created using the rule UUID as application ID, so they share the incoming events

Doing that, I see trouble coming from the number of Kafka Streams threads when many rules are deployed. However, it will allow me to use all features of Kafka Streams to build the topology for a rule (windowing especially). The alternative would be something like the routing scenario in this question, where one processor has all the rules and state, and listens on the two topics. I'm also evaluating Flink, and there I use this idea with a topology similar to [King's RBEA](http://data-artisans.com/rbea-scalable-real-time-analytics-at-king/) service.

I feel like this kind of dynamic scenario is a challenge for current stream processing middlewares, most of which assume a static job that must be redeployed on changes

Sorry for the long post going away from my question, but that adds some context to the problem.

**Comment by miguno** [comment]
@mdemierre: Thanks for taking the time to provide this context, much appreciated!

Question: Have you ever considered using a custom processor (Processor API) that uses Kafka's "normal" consumer client to (fully) read from the `rules-deployment` topic, thus giving each instance of your app a copy of all the rules?  This is a workaround that many users are falling back to until the global state/table feature is available.

**Comment by mdemierre** [comment]
@miguno:
Yes, it may actually be cleaner. The processor would read from the beginning of the `rules-deployment` topic at startup, and then start processing events. But wouldn't it be equivalent to my solution? Each consumer would have to have a different consumer group. Or do you mean using manual partition assignation?

This also introduces another issue I think: how do the two APIs interact? I mean what happens if messages arrive through both API's at the same time? Are both callbacks executed concurrently?

**Comment by miguno** [comment]
@mdemierre: I noticed you updated your last message.  Sorry that I haven't been able to get back to you sooner (the original of the last message still had 1-2 open questions I think).  But it looks like you have been able to come up with a working solution in the meantime. :-)

**Comment by mdemierre** [comment]
@miguno No probem. Actually my questions were answered in the Consumer API docs, so I updated with my solution and closed the issue. Looking forward to those "global" tables/states to simplify the implementation.
