### ISSUE TITLE
kafka streams in Kappa architectire

### ISSUE THREAD

**Issue by mazorigal** [confluentinc/examples#88]
Hi,

I am doing a presentation about Kappa vs Lambda Architecture,
and since Jay Kreps was the one who wrote the article questioning the lambda architecture, and also part of the samza team, I thought this will be good place to ask whether kafka streams can be used in order to implement the Kappa architecture ?
More interesting to me is to understand how kafka streams can be used when a big batch of history data need to be reprocessed (due to code change for example) ? after all the parallelism is limited by the number of topic partitions.
Is kafka streams able somehow to treat the batch as a special case of stream ?

Thanks,

**Comment by miguno** [comment]
> More interesting to me is to understand how kafka streams can be used
> when a big batch of history data need to be reprocessed (due to code change for example) ?

Yes, you can use Kafka's Streams API for this.  Though the community has just begun to make re-processing use cases more convenient to pull off in practice.  For example, the [Application Reset Tool](https://www.confluent.io/blog/data-reprocessing-with-kafka-streams-resetting-a-streams-application/) for Kafka Streams applications was recently added. And as we speak there's more in the pipeline in terms of such functionality.

> Is kafka streams able somehow to treat the batch as a special case of stream ?

Not yet, where the focus is on "yet". The first conversations have already started how to special-case "batch" (aka finite/bounded) processing of data.

**Comment by mazorigal** [comment]
Thanks for the link.
The way how to reset is quite clear but still few things that are missing:

1 - The max parallelism that can be achieved is depends on the number of topic partitions.
     In case reset is required, it means that much more data need to be processed, but the parallelism     cannot be increased (based on the kappa approach, you need start second job of the stream and wait until it catches up the first job - and if the parallelism cannot increased - it can take quite some time to catch up the first streaming app ),
what would be the solution here in order to speed up the reprocessing ? (repartition the original topic to more partitions ? )

2 - assuming that my kafka retention policy is X days, but I still need to keep more aged data, hence the data is also stored in hdfs (append only like the kafka log approach). In case I need to reprocess data older then X days, how can I do it ? (kafka streams can read only from kafka topics vs spark / Flink that can also read directly from hdfs)

**Comment by mjsax** [comment]
> 1 -"repartition the original topic to more partitions ?"

Yes. Overpartitioning  your topic from the beginning on the currently the recommended best-practice advice.

2 - If you know you want to keep data longer, you can always increase retention time. There is no technical reason to not set it to Long.MAX_VALUE (i.e. for practical reasons this means "forever") as long as you have enough disk space. But if you have enough space to store everything you want to keep in HDFS anyway, you could just store everything in Kafka instead and get rid of HDFS.

Or as an alternative, if you have data in HDFS that is no longer available in Kafka, you can just push it to Kafka again (for example using Kafka Connect). Of course, this also take some time if you data set is large...
