### ISSUE TITLE
Library

### ISSUE THREAD

**Issue by trickleup** [confluentinc/examples#97]
Hi,

I wonder if the testing infrastructure files in this repo (embedded kafka, zookeeper, etc. and other boilerplate) are available as a maven dependency?

Thanks for some great examples,
Johan

**Comment by mjsax** [comment]
Not at the moment. There are plan to release them at some point, but there is not concrete timeline.

**Comment by miguno** [comment]
@trickleup: We're currently also assessing what exactly would be helpful to expose/make available.

What kind of functionality would you need?  Is it just the embedded Kafka/ZK/schema registry code, or something in addition/something different?

**Comment by miguno** [comment]
@trickleup:
> Thanks for some great examples,

Thanks, much appreciated, Johan!  Feel free to let us know if we can further improve the examples (are some specific examples missing, are the current ones easy to understand or not, ...).

**Comment by trickleup** [comment]
Thanks for a quick response - I haven't actually used these classes to write my own tests yet, so I'm not 100% sure what the dependencies are, but the classes (and their dependencies) that would be really useful in a package are

- Embedded kafka / zookeeper files
- Integration Test Utils

Basically, my use case is that I want to write simple functional tests that runs over a topology. So anything needed to inject processor context, state stores, etc. in memory, and write assertions on the outcome.
