### ISSUE TITLE
Entire memory (ram) of machine gets exhausted when running kafka-streaming state-store.

### ISSUE THREAD

**Issue by deepakpengoria** [confluentinc/examples#98]
Hi,
I ran my application on AWS machine having 32GB ram. This application is written in Java using Kafka-Streaming low level api which maintain the state using state-store. When I ran it for 72 hours or more and keep on sending load (messages) on kafka-topic then entire memory i.e. 32 GB of aws machine gets exhausted by kafka-streaming application. While I ran my java application with `-xms4gb` and `-xmx12gb` that means my kafka-streaming application can't go beyond 12 GB heap space. As per Kafka-Streaming memory management,  RocksDB uses off-heap space which might be causing this issue. Can you please help me to resolve this problem. I have kafka topic (having 400 partitions) which is being read by kafka-streaming (configured 100 threads) application. Thanks

**Comment by miguno** [comment]
@deepakpengoria: Sorry to hear that.

Could you please post your question to the [Confluent mailing list](https://groups.google.com/forum/?pli=1#!forum/confluent-platform) and/or to the [Kafka user mailing list](https://kafka.apache.org/contact)?  This GitHub repository is not the place to answer questions such as the one above, see https://github.com/confluentinc/examples/tree/3.1.x/kafka-streams#help.

Thanks!
