### ISSUE TITLE
SpecificAvroSerde and GenericAvroSerde

### ISSUE THREAD

**Issue by KyleWinkelman** [confluentinc/examples#99]
I really like the SpecificAvroSerde and GenericAvroSerde api constructed in io.confluent.examples.streams.utils. I was wondering if this is something that will become part of the schema-registry/avro-serializers project. That project works well for Producers and Consumers but it isn't so friendly with Streams.
I was hoping the author could submit a pull request to the schema-registry/avro-serializers project.

**Comment by miguno** [comment]
Yes, there's already a pending PR at https://github.com/confluentinc/schema-registry/pull/442.  Please stay tuned!
