### ISSUE TITLE
Start.sh does not detect ccloud

### ISSUE THREAD

**Issue by gaukharaya** [confluentinc/examples#997]
Hi, 

I have ccloud installed and its login is saved, however when I run ./start.sh the script fails with 'ccloud' is not found.

![image](https://user-images.githubusercontent.com/9504353/119855452-d4290100-bf09-11eb-9b68-eb45d0e8f115.png)

**Environment**
 - GitHub branch: `6.1.1-post`
 - Operating System: Ubuntu 20.04.2 LTS
 - Version of Docker: Docker version 20.10.6, build 370c289
 - Version of Docker Compose: docker-compose version 1.29.2, build 5becea4c

**Comment by ybyzek** [comment]
@gaukharaya this line is how `ccloud` is checked: https://github.com/confluentinc/examples/blob/6.1.1-post/utils/ccloud_library.sh#L70

Maybe you can try the command on its own to see what happens? `type ccloud`

**Comment by gaukharaya** [comment]
Thank you for speedy response, I am on windows and was using alias. 

`type ccloud` returned `ccloud is aliased to `ccloud.exe'`

I modified `ccloud` reference to `ccloud.exe` in `ccloud_library.sh` as a workaround
